add_newline = false 
command_timeout = 200
[line_break]
disabled = true

# format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[ ](bold cyan)"
success_symbol = "[ ](bold cyan)"

[username]
# style_user = "bold "
show_always = true 

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold green"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_branch]
format = "[ $branch]($style) "
style = "italic red"

[git_status]
format     = '[$all_status]($style)'
style      = "italic red"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? ${count} "
modified   = " "
stashed    = " ${count} "
staged     = " ${count} "
renamed    = ""
deleted    = ""

[package]
disabled = true
[dotnet]
disabled = true

