add_newline = false 
command_timeout = 200
[line_break]
disabled = true

format = "$username$hostname$directory$git_branch$git_status$cmd_duration$character"

[character]
error_symbol = "[ ](bold #eb6f92)" # mError
success_symbol = "[ ](bold #9ccfd8)" # mSecondary

[username]
style_user = "bold #e0def4" # mOnSurface
show_always = true

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold #ebbcba" # mPrimary
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "#e0def4" # mOnSurface

[git_commit]
commit_hash_length = 8
style = "bold #908caa" # mOnSurfaceVariant

[git_branch]
format = "[ $branch]($style) "
style = "italic #9ccfd8" # mSecondary

[git_status]
format     = '[$all_status]($style)'
style      = "italic #9ccfd8" # mSecondary
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = "[](#eb6f92)" # mError
up_to_date = " "
untracked  = "[? ${count}](#ebbcba)" # mPrimary
modified   = "[ ](#ebbcba)" # mPrimary
stashed    = "[ ${count}](#908caa)" # mOnSurfaceVariant
staged     = "[ ${count}](#ebbcba)" # mPrimary
renamed    = ""
deleted    = ""

[package]
disabled = true
[dotnet]
disabled = true

